name: Run Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.31-strict/stable
          juju-channel: 3.6

      - name: Run integration tests
        run: tox -e integration -- --model testing

      - name: Get contexts
        run: kubectl config view
        if: failure()

      - name: Get juju status
        run: juju status --relations

      - name: Get juju logs
        run: juju debug-log --replay
